name: medora
description: AI-Powered Healthcare Platform

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.2
  firebase_core: ^2.15.0
  firebase_auth: ^4.12.0
  cloud_firestore: ^4.9.0
  firebase_storage: ^11.2.0
  google_sign_in: ^6.1.0
  provider: ^6.1.1
  flutter_svg: ^2.0.7
  geolocator: ^11.0.0
  google_maps_flutter: ^2.2.3
  image_picker: ^1.0.4
  http: ^1.1.0
  shared_preferences: ^2.2.2
  intl: ^0.20.2
  firebase_ui_auth: ^1.1.0
  firebase_ui_oauth_google: ^1.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  generate: true
  
  assets:
    - assets/images/
    - assets/icons/
    # Remove font references since we don't have the font files