// File generated by FlutterFire CLI - run `flutterfire configure` to regenerate
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDaTcBBeEOmpVdldwMqMpOqdsdJulOU_UE',
    appId: '1:643095045949:android:8e0eac6154e1c144dac754',
    messagingSenderId: '643095045949',
    projectId: 'medora-bb341',
    storageBucket: 'medora-bb341.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA4dHKJgFzmqwSadWBfJ76xH17YcIeBI0s',
    appId: '1:643095045949:ios:fc344b20d3d36877dac754',
    messagingSenderId: '643095045949',
    projectId: 'medora-bb341',
    storageBucket: 'medora-bb341.firebasestorage.app',
    androidClientId: '643095045949-1em27kkur65ds298i0f7t6li5bnnqo9v.apps.googleusercontent.com',
    iosClientId: '643095045949-1q75pfu62ooiv9ce61l0au31n1rhsc5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.medoraNew',
  );

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAY6PsfhcpbA_qhkDqeY76OL4j5dK_YxiA',
    appId: '1:643095045949:web:76ae3cb8653c47c1dac754',
    messagingSenderId: '643095045949',
    projectId: 'medora-bb341',
    authDomain: 'medora-bb341.firebaseapp.com',
    storageBucket: 'medora-bb341.firebasestorage.app',
    measurementId: 'G-FZBMV26LL9',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA4dHKJgFzmqwSadWBfJ76xH17YcIeBI0s',
    appId: '1:643095045949:ios:fc344b20d3d36877dac754',
    messagingSenderId: '643095045949',
    projectId: 'medora-bb341',
    storageBucket: 'medora-bb341.firebasestorage.app',
    androidClientId: '643095045949-1em27kkur65ds298i0f7t6li5bnnqo9v.apps.googleusercontent.com',
    iosClientId: '643095045949-1q75pfu62ooiv9ce61l0au31n1rhsc5s.apps.googleusercontent.com',
    iosBundleId: 'com.example.medoraNew',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAY6PsfhcpbA_qhkDqeY76OL4j5dK_YxiA',
    appId: '1:643095045949:web:6567fcd9ec953ffbdac754',
    messagingSenderId: '643095045949',
    projectId: 'medora-bb341',
    authDomain: 'medora-bb341.firebaseapp.com',
    storageBucket: 'medora-bb341.firebasestorage.app',
    measurementId: 'G-YLH172EN7Z',
  );

}